name: Npmrc
description: Create npmrc file with GITHUB_TOKEN

runs:
  using: "composite"
  steps:
    - name: Create npmrc file with GITHUB_TOKEN
      id: generate-npmrc
      run: |
        echo '@cyber-cats:registry=https://npm.pkg.github.com/cyber-cats\n always-auth=true\n //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}\n //npm.pkg.github.com/cyber-cats/:_authToken=${GITHUB_TOKEN}' > ${{ github.workspace }}/.npmrc
        cat .npmrc
      shell: bash
