name: Npmrc
description: Create npmrc file with GITHUB_TOKEN

runs:
  using: "composite"
  steps:
    - name: Create npmrc file with GITHUB_TOKEN
      id: generate-npmrc
      run: |
        cp ${{ github.workspace }}/.npmrc-ci ${{ github.workspace }}/.npmrc
        cat .npmrc
      shell: bash
