name: Web Development Deploy
on:
  push:
    branches:
      - main

jobs:

  build:
    name: build
    runs-on: ubuntu-18.04
    name: build
    steps:
      - name: Build
        uses: ./.github/actions/generate-npmrc
